# Dependencies
markdown:         redcarpet
pygments:         false

# Permalinks
permalink:        pretty

# Setup
title:            per.halleluja.nu
name:             per.halleluja.nu
paginate:         10
