# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:
    - autolink

# Permalinks
permalink:        pretty

# Setup
title:            per.halleluja.nu
name:             per.halleluja.nu
paginate:         10
